import os
from sentence_transformers import SentenceTransformer, CrossEncoder
from upstash_vector import Index

# Models (loaded once on demand)
_embedder = None
_reranker = None
_index = None

def _load_models():
    global _embedder, _reranker, _index

    if _embedder is None:
        print("Loading embedding model...")
        _embedder = SentenceTransformer("all-MiniLM-L6-v2")

    if _reranker is None:
        print("Loading reranker model...")
        _reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

    if _index is None:
        print("Connecting to Upstash Vector...")
        url = os.environ.get("UPSTASH_VECTOR_URL") or os.environ.get("UPSTASH_VECTOR_REST_URL")
        token = os.environ.get("UPSTASH_VECTOR_TOKEN") or os.environ.get("UPSTASH_VECTOR_REST_TOKEN")
        
        if not url or not token:
            print("WARNING: Upstash Vector credentials not set.")
            # We don't raise error here to avoid crashing the app on boot if not configured
            return
            
        _index = Index(url=url, token=token)

def retrieve(query: str, top_k: int = 5, tags: list = None) -> list[str]:
    """
    Retrieve relevant context for a farmer query.
    Uses semantic search + cross-encoder reranking.
    Optionally filters by tags (e.g. ["disease_pest", "crop"]).
    """
    _load_models()
    
    if _index is None:
        return ["Knowledge base is currently unavailable."]

    # Step 1: Embed the query
    query_vector = _embedder.encode(query).tolist()

    # Step 2: Search Upstash Vector (get broader set for reranking)
    try:
        results = _index.query(
            vector=query_vector,
            top_k=15,
            include_metadata=True
        )
    except Exception as e:
        print(f"Error querying Upstash: {e}")
        return []

    if not results:
        return []

    # Step 3: Optional tag filtering
    if tags:
        results = [
            r for r in results
            if any(t in r.metadata.get("tags", []) for t in tags)
        ]

    # Step 4: Rerank with cross-encoder for better precision
    # We retrieve the "answer" field from metadata (which was generated by LLM in Task 2)
    candidates = [r.metadata.get("answer", "") for r in results if r.metadata]

    if not candidates:
        return []

    pairs = [(query, candidate) for candidate in candidates]
    scores = _reranker.predict(pairs)

    # Sort by reranker score and return top_k
    ranked = sorted(
        zip(scores, candidates),
        key=lambda x: x[0],
        reverse=True
    )

    return [answer for _, answer in ranked[:top_k]]
